# Generated by Django 5.2.8 on 2025-11-20 15:21

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the history entry", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for anchor links",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the entry was created",
                    ),
                ),
                (
                    "content",
                    markdownfield.models.MarkdownField(
                        help_text="History entry content in Markdown format",
                        rendered_field="content_rendered",
                    ),
                ),
                ("content_rendered", markdownfield.models.RenderedMarkdownField()),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the entry is visible to the public",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Entry",
                "verbose_name_plural": "History Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
