# Generated by Django 5.2.8 on 2025-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or caption for the photo (for identification)",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Photo file to upload", upload_to="photos/"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the photo was uploaded",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
