# Generated by Django 5.2.8 on 2025-11-23 22:33

import datetime
import django.db.models.deletion
import markdownfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0002_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the blog post", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Optional subtitle for the blog post",
                        max_length=300,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the post",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "display_author",
                    models.CharField(
                        help_text="Author name as displayed on the post", max_length=100
                    ),
                ),
                (
                    "content",
                    markdownfield.models.MarkdownField(
                        help_text="Blog post content in Markdown format",
                        rendered_field="content_rendered",
                    ),
                ),
                ("content_rendered", markdownfield.models.RenderedMarkdownField()),
                (
                    "display_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date to display on the post (defaults to creation date)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the post was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the post was last updated",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the post is published. Unpublished posts are pending review.",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-display_date", "-created_at"],
            },
        ),
    ]
