# Generated by Django 5.2.16 on 2026-08-18 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0003_add_blogpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="display_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date to display on the post (defaults to creation date)",
            ),
        ),
    ]
