# Generated by Django 5.2.17 on 2026-09-09 23:56

import atheweb.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0004_alter_blogpost_display_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=atheweb.fields.DownscaledImageField(
                help_text="Photo file to upload",
                max_dimension=2048,
                to_jpeg=False,
                upload_to="photos/",
            ),
        ),
    ]
