# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0005_alter_photo_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Photo for blog posts",
                "verbose_name_plural": "Photos for blog posts",
            },
        ),
    ]
