# Generated by Django 5.2.8 on 2025-11-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0019_alter_student_house"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "club",
                    models.ForeignKey(
                        limit_choices_to={"is_club": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ta_attendance_records",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ta_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "club__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "club"), name="unique_user_date_club"
                    )
                ],
            },
        ),
    ]
