# Generated by Django 5.2.8 on 2025-11-22 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp for when the record was submitted.",
            ),
            preserve_default=False,
        ),
    ]
