# Generated by Django 5.2.17 on 2026-09-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0029_course_kind"),
        ("ta_attendance", "0002_attendance_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="club",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("kind", "class"), _negated=True),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ta_attendance_records",
                to="courses.course",
            ),
        ),
    ]
