# Generated by Django 5.2.8 on 2025-11-14 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("home", "0002_alter_staffphotolisting_ordering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                blank=True,
                help_text="Estimate of the difficulty of this course.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                help_text="Link to the instructor for this course.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="home.staffphotolisting",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="lesson_plan",
            field=models.TextField(
                blank=True,
                help_text="List of lessons planned for this course. One per line.",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="end_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When this semester ends"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="semester",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When this semester starts"
            ),
            preserve_default=False,
        ),
    ]
