# Generated by Django 5.2.8 on 2025-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_difficulty_course_instructor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="end_date",
            field=models.DateField(help_text="When this semester ends"),
        ),
        migrations.AlterField(
            model_name="semester",
            name="start_date",
            field=models.DateField(help_text="When this semester starts"),
        ),
    ]
