# Generated by Django 5.2.8 on 2025-11-14 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_semester_end_date_alter_semester_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={"ordering": ("-start_date",)},
        ),
    ]
