# Generated by Django 5.2.8 on 2025-11-14 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_semester_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ("-semester__start_date", "name")},
        ),
    ]
