# Generated by Django 5.2.8 on 2025-11-14 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discord_role_id",
            field=models.CharField(
                blank=True,
                help_text="Discord role ID to mention in reminders.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="discord_webhook",
            field=models.URLField(
                blank=True, help_text="Discord webhook URL for posting reminders."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="google_classroom_direct_link",
            field=models.URLField(
                blank=True,
                help_text="Direct link to the Google Classroom for this course.",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="google_classroom_join_link",
            field=models.URLField(
                blank=True,
                help_text="Join link for students to join the Google Classroom.",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="regular_meeting_time",
            field=models.CharField(
                blank=True,
                help_text="Regular meeting time for this course, e.g. '5pm-6pm ET on Saturday'.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="zoom_meeting_link",
            field=models.URLField(
                blank=True, help_text="Zoom meeting link for this course."
            ),
        ),
        migrations.CreateModel(
            name="CourseMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When this meeting starts."),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Topic for this lecture.", max_length=200
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a reminder has been sent for this meeting.",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ("start_time",),
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_students",
                        to="courses.course",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="courses.semester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-semester__start_date", "user__username"),
                "unique_together": {("user", "semester")},
            },
        ),
    ]
