# Generated by Django 5.2.8 on 2025-11-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_discord_role_id_course_discord_webhook_and_more"),
        ("home", "0004_alter_staffphotolisting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the instructor for this course.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="home.staffphotolisting",
            ),
        ),
    ]
