# Generated by Django 5.2.8 on 2025-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_course_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_club",
            field=models.BooleanField(
                default=False, help_text="Whether this is a club (vs. a class)."
            ),
        ),
    ]
