# Generated by Django 5.2.8 on 2025-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_is_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemeeting",
            name="title",
            field=models.CharField(
                blank=True, help_text="Topic for this lecture.", max_length=200
            ),
        ),
    ]
