# Generated by Django 5.2.8 on 2025-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discord_reminders_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether to send Discord reminders."
            ),
        ),
    ]
