# Generated by Django 5.2.8 on 2025-11-19 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_course_discord_reminders_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="leaders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can manage this course and its meetings.",
                related_name="led_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
