# Generated by Django 5.2.8 on 2025-11-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_course_discord_reminders_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="house_points_freeze_date",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, leaderboard shows only points awarded up to this date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="house",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blob", "Blob"),
                    ("cat", "Cat"),
                    ("owl", "Owl"),
                    ("red_panda", "Red Panda"),
                    ("bunny", "Bunny"),
                ],
                help_text="House assignment for this semester",
                max_length=20,
            ),
        ),
    ]
