# Generated by Django 5.2.8 on 2025-11-20 13:43

from django.db import migrations, models


def transfer_enrollments(apps, schema_editor):
    """Transfer enrollments from Student.enrolled_courses to Course.students."""
    Student = apps.get_model("courses", "Student")
    Course = apps.get_model("courses", "Course")

    # Iterate through all students and transfer their enrollments
    for student in Student.objects.all():
        for course in student.enrolled_courses.all():
            course.students.add(student)


def reverse_transfer_enrollments(apps, schema_editor):
    """Reverse transfer: from Course.students back to Student.enrolled_courses."""
    Student = apps.get_model("courses", "Student")
    Course = apps.get_model("courses", "Course")

    # Iterate through all courses and reverse transfer their enrollments
    for course in Course.objects.all():
        for student in course.students.all():
            student.enrolled_courses.add(course)


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_merge_20251119_2128"),
    ]

    operations = [
        # First, add the new field
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students enrolled in this course.",
                related_name="new_enrolled_courses",
                to="courses.student",
            ),
        ),
        # Transfer data from old field to new field
        migrations.RunPython(transfer_enrollments, reverse_transfer_enrollments),
        # Remove the old field
        migrations.RemoveField(
            model_name="student",
            name="enrolled_courses",
        ),
        # Rename the related_name to the correct one
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students enrolled in this course.",
                related_name="enrolled_courses",
                to="courses.student",
            ),
        ),
    ]
