# Generated by Django 5.2.8 on 2025-11-20 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_remove_student_enrolled_courses_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="google_classroom_join_link",
        ),
    ]
