# Generated by Django 5.2.8 on 2025-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_remove_course_google_classroom_join_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, this semester will be hidden from non-staff users",
            ),
        ),
    ]
