# Generated by Django 5.2.8 on 2025-11-21 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_semester_visible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ("-semester__start_date", "airtable_name")},
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="student",
            name="airtable_name",
            field=models.CharField(
                default="Evil Chin",
                help_text="A unique name for the student, as listed in Airtable. This is used to disambiguate students during the registration process and when awarding house points, but generally doesn't appear to students.",
                max_length=80,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "semester"),
                name="unique_user_per_semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("airtable_name", "semester"),
                name="unique_airtable_name_per_semester",
            ),
        ),
    ]
