# Generated by Django 5.2.8 on 2025-11-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0017_alter_student_options_alter_student_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="discord_reminders_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether to send Discord reminders."
            ),
        ),
    ]
