# Generated by Django 5.2.8 on 2025-11-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_alter_course_discord_reminders_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="house",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blob", "Blobs"),
                    ("cat", "Cats"),
                    ("owl", "Owls"),
                    ("red_panda", "Red Panda"),
                    ("bunny", "Bunnies"),
                ],
                help_text="House assignment for this semester",
                max_length=20,
            ),
        ),
    ]
