# Generated by Django 5.2.8 on 2025-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_alter_student_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="house_points_class_threshold",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Number of class attendances worth 5 points; subsequent are worth 3",
            ),
        ),
    ]
