# Generated by Django 5.2.8 on 2025-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_add_house_points_class_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="house",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blob", "Blobs"),
                    ("bunny", "Bunnies"),
                    ("cat", "Cats"),
                    ("owl", "Owls"),
                    ("red_panda", "Red Panda"),
                ],
                help_text="House assignment for this semester",
                max_length=20,
            ),
        ),
    ]
