# Generated by Django 5.2.8 on 2025-12-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_alter_student_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the event.", max_length=200),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When this event starts."),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the event."
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="Optional link (e.g. Zoom meeting link)."
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_events",
                        to="courses.semester",
                    ),
                ),
            ],
            options={
                "ordering": ("start_time",),
            },
        ),
    ]
