# Generated by Django 5.2.17 on 2026-08-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_add_calendar_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="president_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the student president running this semester. Shown to students on the dashboard while they wait on class and house assignments.",
                max_length=100,
            ),
        ),
    ]
