# Generated by Django 5.2.17 on 2026-08-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_semester_president_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="semester_starts_before_it_ends",
            ),
        ),
    ]
