# Generated by Django 5.2.7, then reordered by hand so that the leaders each
# course had can be carried over before the field goes away.

from django.db import migrations, models


def split_up_leaders(apps, schema_editor):
    """Send every leader to whichever of the two new fields fits them.

    Leaders were doing two unrelated jobs: saying who could edit a course, and
    saying whose course it was. Editing now follows from what someone is, so
    what needs carrying over is only whose pages a course shows up on, and
    that is recorded differently for staff and for students. A leader who is
    neither has nowhere to go, so they are named in the output rather than
    dropped quietly.
    """
    Course = apps.get_model("courses", "Course")
    StaffPhotoListing = apps.get_model("home", "StaffPhotoListing")
    Student = apps.get_model("courses", "Student")

    dropped = []
    for course in Course.objects.prefetch_related("leaders").select_related(
        "instructor"
    ):
        instructor_user_id = (
            course.instructor.user_id if course.instructor is not None else None
        )
        for user in course.leaders.all():
            if user.pk == instructor_user_id:
                continue  # already the instructor, nothing to record
            listing = StaffPhotoListing.objects.filter(user=user).first()
            if listing is not None:
                course.subscribed_staff.add(listing)
                continue
            student = Student.objects.filter(
                user=user, semester=course.semester_id
            ).first()
            if student is not None:
                course.student_organizers.add(student)
            else:
                dropped.append((course, user))

    if dropped:
        print("\nThese leaders were neither staff nor enrolled, and were dropped:")
        for course, user in dropped:
            print(f"  - {user.username} on {course.name}")
        print("Add them back by hand if they still need to edit one.\n")


def rebuild_leaders(apps, schema_editor):
    """Put everyone attached to a course back into leaders."""
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.prefetch_related(
        "subscribed_staff", "student_organizers"
    ).select_related("instructor"):
        users = [
            listing.user_id
            for listing in course.subscribed_staff.all()
            if listing.user_id is not None
        ]
        users += [
            student.user_id
            for student in course.student_organizers.all()
            if student.user_id is not None
        ]
        if course.instructor is not None and course.instructor.user_id is not None:
            users.append(course.instructor.user_id)
        course.leaders.add(*users)


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_semester_semester_starts_before_it_ends"),
        ("home", "0013_alter_applypset_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subscribed_staff",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff who follow this course, whether they run it, help with it or just want it on their calendar. Staff subscribe themselves from the course page; it puts the course on their own pages and is not shown to anyone else. It grants nothing: staff editing rights come from being staff.",
                related_name="subscribed_courses",
                to="home.staffphotolisting",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="student_organizers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who run this course themselves, for the handful of student-led clubs. They may edit it and schedule its meetings, and are credited on its page. Staff do not belong here: their editing rights come from being staff.",
                related_name="organized_courses",
                to="courses.student",
            ),
        ),
        migrations.RunPython(split_up_leaders, rebuild_leaders),
        migrations.RemoveField(
            model_name="course",
            name="leaders",
        ),
    ]
