# Generated by Django 5.2.7, then reordered by hand so that the leaders each
# course had can be carried over to co_instructors before the field goes away.

from django.db import migrations, models


def leaders_to_co_instructors(apps, schema_editor):
    """Credit every leader who is staff as a co-instructor.

    Leaders were doing two unrelated jobs: saying who could edit a course, and
    saying whose course it was. Editing is now decided by being staff, so only
    the second job needs carrying over, and only for leaders with a staff
    listing to be credited on. A leader without one is a student who was given
    edit rights by hand; there is nowhere for them to go, so they are named in
    the output rather than dropped quietly.
    """
    Course = apps.get_model("courses", "Course")
    StaffPhotoListing = apps.get_model("home", "StaffPhotoListing")

    dropped = []
    for course in Course.objects.prefetch_related("leaders").select_related(
        "instructor"
    ):
        instructor_user_id = (
            course.instructor.user_id if course.instructor is not None else None
        )
        for user in course.leaders.all():
            if user.pk == instructor_user_id:
                continue  # already the instructor, nothing to record
            listing = StaffPhotoListing.objects.filter(user=user).first()
            if listing is None:
                dropped.append((course, user))
            else:
                course.co_instructors.add(listing)

    if dropped:
        print("\nThese leaders had no staff listing and were not carried over:")
        for course, user in dropped:
            print(f"  - {user.username} on {course.name}")
        print("Give them a StaffPhotoListing if they still need to edit a club.\n")


def co_instructors_to_leaders(apps, schema_editor):
    """Rebuild leaders from whoever is credited with running the course."""
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.prefetch_related("co_instructors").select_related(
        "instructor"
    ):
        users = [
            listing.user_id
            for listing in course.co_instructors.all()
            if listing.user_id is not None
        ]
        if course.instructor is not None and course.instructor.user_id is not None:
            users.append(course.instructor.user_id)
        course.leaders.add(*users)


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_semester_semester_starts_before_it_ends"),
        ("home", "0013_alter_applypset_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="co_instructors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other staff who run this course alongside the instructor. Credits them on the course page and lists it among their own courses; editing rights come from being staff, not from this field.",
                related_name="co_instructed_courses",
                to="home.staffphotolisting",
            ),
        ),
        migrations.RunPython(
            leaders_to_co_instructors,
            co_instructors_to_leaders,
        ),
        migrations.RemoveField(
            model_name="course",
            name="leaders",
        ),
    ]
