# Generated by Django 5.2.17 on 2026-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0026_course_subscribed_staff_student_organizers"),
        ("home", "0014_alter_staffphotolisting_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_office_hours",
            field=models.BooleanField(
                default=False,
                help_text="Whether this club is a weekly office hours session, whose meetings students may send questions to.",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_office_hours", False), ("is_club", True), _connector="OR"
                ),
                name="office_hours_must_be_a_club",
            ),
        ),
    ]
