# Generated by Django 5.2.8 on 2025-11-14 03:47

import django.db.models.deletion
import markdownfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPhotoListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name to display on the staff page", max_length=100
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role/title (e.g., President)", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("board", "Board"),
                            ("teachers", "Teachers"),
                            ("tas", "TAs"),
                            ("past", "Past Staff"),
                        ],
                        help_text="Staff category",
                        max_length=20,
                    ),
                ),
                (
                    "biography",
                    markdownfield.models.MarkdownField(
                        help_text="Biography in Markdown format",
                        rendered_field="biography_rendered",
                    ),
                ),
                ("biography_rendered", markdownfield.models.RenderedMarkdownField()),
                (
                    "photo",
                    models.ImageField(
                        help_text="Staff member photo", upload_to="staff_photos/"
                    ),
                ),
                (
                    "ordering",
                    models.IntegerField(
                        default=0,
                        help_text="Ordering priority (0 for alphabetical, higher numbers come first)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Django user account for this staff member",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Photo Listing",
                "verbose_name_plural": "Staff Photo Listings",
                "ordering": ["-ordering", "display_name"],
            },
        ),
    ]
