# Generated by Django 5.2.8 on 2025-11-14 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffphotolisting",
            name="ordering",
            field=models.IntegerField(
                default=0, help_text="Ordering priority (higher numbers come first)"
            ),
        ),
        migrations.AlterField(
            model_name="staffphotolisting",
            name="role",
            field=models.CharField(help_text="Role or title", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffphotolisting",
            name="user",
            field=models.OneToOneField(
                help_text="Django user account for this staff member",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
