# Generated by Django 5.2.8 on 2025-11-14 (manually created)

import re

from django.db import migrations, models
from django.utils.text import slugify


def generate_slug_from_name(display_name: str) -> str:
    """Generate a slug from a display name."""
    # Remove content in parentheses and slugify
    name = re.sub(r"\s*\([^)]*\)", "", display_name)
    slug = slugify(name)
    return slug


def populate_slugs(apps, schema_editor):
    """Populate slug field from display_name for existing records."""
    StaffPhotoListing = apps.get_model("home", "StaffPhotoListing")
    for staff in StaffPhotoListing.objects.all():
        staff.slug = generate_slug_from_name(staff.display_name)
        staff.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_staffphotolisting_ordering_and_more"),
    ]

    operations = [
        # Step 1: Add slug field as nullable
        migrations.AddField(
            model_name="staffphotolisting",
            name="slug",
            field=models.SlugField(
                max_length=100,
                null=True,
                help_text="URL-friendly slug for staff member",
            ),
        ),
        # Step 2: Populate slugs from display names
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        # Step 3: Make slug non-nullable and unique
        migrations.AlterField(
            model_name="staffphotolisting",
            name="slug",
            field=models.SlugField(
                unique=True,
                max_length=100,
                help_text="URL-friendly slug for staff member",
            ),
        ),
    ]
