# Generated by Django 5.2.8 on 2025-11-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_staffphotolisting_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffphotolisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("board", "Board"),
                    ("teachers", "Current Instructors"),
                    ("tas", "TAs"),
                    ("past", "Past Staff"),
                ],
                help_text="Staff category",
                max_length=20,
            ),
        ),
    ]
