# Generated by Django 5.2.8 on 2025-11-14 17:34

from django.db import migrations


def rename_categories_forward(apps, schema_editor):
    """Rename staff categories to new naming scheme."""
    StaffPhotoListing = apps.get_model("home", "StaffPhotoListing")

    # Mapping of old category names to new category names
    category_mapping = {
        "teachers": "instructor",
        "tas": "ta",
        "past": "xstaff",
        # "board" stays the same
    }

    for old_name, new_name in category_mapping.items():
        StaffPhotoListing.objects.filter(category=old_name).update(category=new_name)


def rename_categories_reverse(apps, schema_editor):
    """Reverse the category rename operation."""
    StaffPhotoListing = apps.get_model("home", "StaffPhotoListing")

    # Reverse mapping
    reverse_mapping = {
        "instructor": "teachers",
        "ta": "tas",
        "xstaff": "past",
        # "board" stays the same
    }

    for new_name, old_name in reverse_mapping.items():
        StaffPhotoListing.objects.filter(category=new_name).update(category=old_name)


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_staffphotolisting_category"),
    ]

    operations = [
        migrations.RunPython(rename_categories_forward, rename_categories_reverse),
    ]
