# Generated by Django 5.2.8 on 2025-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_rename_staff_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffphotolisting",
            options={
                "ordering": ["category", "-ordering", "display_name"],
                "verbose_name": "Staff Photo Listing",
                "verbose_name_plural": "Staff Photo Listings",
            },
        ),
        migrations.AlterField(
            model_name="staffphotolisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("board", "Board"),
                    ("instructor", "Current Instructors"),
                    ("ta", "TAs"),
                    ("xstaff", "Past Staff"),
                ],
                help_text="Staff category",
                max_length=20,
            ),
        ),
    ]
