# Generated by Django 5.2.8 on 2025-11-20 15:12

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_staffphotolisting_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyPSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the problem set (e.g., 'Fall 2025 PSet')",
                        max_length=200,
                    ),
                ),
                ("deadline", models.DateTimeField(help_text="Application deadline")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        help_text="Status of the problem set",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF file for the problem set",
                        upload_to="apply_psets/",
                    ),
                ),
                (
                    "instructions",
                    markdownfield.models.MarkdownField(
                        help_text="Instructions displayed when status is active (Markdown format)",
                        rendered_field="instructions_rendered",
                    ),
                ),
                ("instructions_rendered", markdownfield.models.RenderedMarkdownField()),
                (
                    "closed_message",
                    markdownfield.models.MarkdownField(
                        help_text="Message displayed when applications are closed (Markdown format)",
                        rendered_field="closed_message_rendered",
                    ),
                ),
                (
                    "closed_message_rendered",
                    markdownfield.models.RenderedMarkdownField(),
                ),
            ],
            options={
                "verbose_name": "Application Problem Set",
                "verbose_name_plural": "Application Problem Sets",
                "ordering": ["-deadline"],
            },
        ),
    ]
