# Generated by Django 5.2.8 on 2025-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_applypset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applypset",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="PDF file for the problem set",
                null=True,
                upload_to="apply_psets/",
            ),
        ),
    ]
