# Generated by Django 5.2.8 on 2025-11-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_applypset_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applypset",
            name="name",
            field=models.CharField(
                help_text="Name of the problem set (e.g., 'Fall 2025')", max_length=200
            ),
        ),
    ]
