# Generated by Django 5.2.8 on 2025-11-20 23:12

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_applypset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applypset",
            name="closed_message",
            field=markdownfield.models.MarkdownField(
                blank=True,
                help_text="Message displayed when applications are closed (Markdown format)",
                rendered_field="closed_message_rendered",
            ),
        ),
        migrations.AlterField(
            model_name="applypset",
            name="instructions",
            field=markdownfield.models.MarkdownField(
                blank=True,
                help_text="Instructions displayed when status is active (Markdown format)",
                rendered_field="instructions_rendered",
            ),
        ),
    ]
