# Generated by Django 5.2.8 on 2025-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_staffphotolisting_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffphotolisting",
            name="discord_username",
            field=models.CharField(
                blank=True, help_text="Discord username", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="staffphotolisting",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Contact email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="staffphotolisting",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="GitHub username", max_length=39
            ),
        ),
        migrations.AddField(
            model_name="staffphotolisting",
            name="instagram_username",
            field=models.CharField(
                blank=True, help_text="Instagram username (without @)", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="staffphotolisting",
            name="website",
            field=models.URLField(blank=True, help_text="Personal website URL"),
        ),
    ]
