# Generated by Django 5.2.8 on 2026-01-03 19:54

from django.db import migrations, models


def convert_datetime_to_date(apps, schema_editor):
    """Convert existing datetime values to date values, preserving the date portion."""
    ApplyPSet = apps.get_model("home", "ApplyPSet")
    for pset in ApplyPSet.objects.all():
        # Convert datetime to date by extracting the date portion
        if pset.deadline:
            pset.deadline_date = pset.deadline.date()
            pset.save(update_fields=["deadline_date"])


def reverse_convert(apps, schema_editor):
    """Reverse migration: convert date back to datetime."""
    ApplyPSet = apps.get_model("home", "ApplyPSet")
    for pset in ApplyPSet.objects.all():
        # Convert date to datetime (midnight on that date)
        if pset.deadline_date:
            # Import datetime here to avoid issues with migrations
            from datetime import datetime

            pset.deadline = datetime.combine(pset.deadline_date, datetime.min.time())
            pset.save(update_fields=["deadline"])


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_add_staff_social_fields"),
    ]

    operations = [
        # Step 1: Add temporary date field
        migrations.AddField(
            model_name="applypset",
            name="deadline_date",
            field=models.DateField(null=True, help_text="Application deadline"),
        ),
        # Step 2: Migrate data from datetime to date
        migrations.RunPython(convert_datetime_to_date, reverse_convert),
        # Step 3: Remove old datetime field
        migrations.RemoveField(
            model_name="applypset",
            name="deadline",
        ),
        # Step 4: Rename date field to original name
        migrations.RenameField(
            model_name="applypset",
            old_name="deadline_date",
            new_name="deadline",
        ),
        # Step 5: Make the field non-nullable
        migrations.AlterField(
            model_name="applypset",
            name="deadline",
            field=models.DateField(help_text="Application deadline"),
        ),
    ]
