# Generated by Django 5.2.17 on 2026-09-09 23:42

import atheweb.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_applypset_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffphotolisting",
            name="photo",
            field=atheweb.fields.DownscaledImageField(
                help_text="Staff member photo", upload_to="staff_photos/"
            ),
        ),
    ]
