# Generated by Django 5.2.8 on 2025-11-20 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffInviteLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this invite link (e.g., 'Spring 2025 Instructors')",
                        max_length=100,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        help_text="Date and time when this invite link expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Staff Invite Link",
                "verbose_name_plural": "Staff Invite Links",
                "ordering": ["-created_at"],
            },
        ),
    ]
