# Generated by Django 5.2.8 on 2025-11-21 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0017_alter_student_options_alter_student_unique_together_and_more",
        ),
        ("reg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInviteLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this invite link (e.g., 'Spring 2025 Students')",
                        max_length=100,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        help_text="Date and time when this invite link expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="The semester this invite link is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_links",
                        to="courses.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Invite Link",
                "verbose_name_plural": "Student Invite Links",
                "ordering": ["-created_at"],
            },
        ),
    ]
