# Generated by Django 5.2.17 on 2026-08-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reg", "0002_studentinvitelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffinvitelink",
            name="name",
            field=models.CharField(
                help_text="A descriptive name for this invite link, e.g. 'Spring 2025'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="studentinvitelink",
            name="name",
            field=models.CharField(
                help_text="A descriptive name for this invite link, e.g. 'Spring 2025'",
                max_length=100,
            ),
        ),
    ]
