# Generated by Django 5.2.17 on 2026-08-26 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_add_calendar_token"),
        ("reg", "0003_alter_staffinvitelink_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email you check regularly; this is the primary email you will receive notifications through",
                        max_length=254,
                    ),
                ),
                (
                    "parent_email",
                    models.EmailField(
                        help_text="A parent or guardian's email, for payment purposes",
                        max_length=254,
                    ),
                ),
                (
                    "discord_username",
                    models.CharField(
                        help_text="Your Discord username, e.g. vEnhance",
                        max_length=64,
                    ),
                ),
                (
                    "taken_class_before",
                    models.BooleanField(
                        help_text="Whether the student has taken an Athemath class before"
                    ),
                ),
                (
                    "course_comments",
                    models.TextField(
                        blank=True,
                        help_text="Anything else to say about class preferences",
                    ),
                ),
                (
                    "availability",
                    models.JSONField(
                        default=list,
                        help_text="Slot keys the student is available for, e.g. ['sat-0830', ...]",
                    ),
                ),
                (
                    "availability_comments",
                    models.TextField(
                        blank=True, help_text="Anything else to say about availability"
                    ),
                ),
                (
                    "quiz_challenge",
                    models.CharField(
                        choices=[
                            ("plan", "I make a plan and act accordingly"),
                            (
                                "big_picture",
                                "I think about the bigger picture and act with intention",
                            ),
                            ("creative", "I look for creative and unique angles"),
                            (
                                "consult",
                                "I consult other people and make sure everyone's on the same page",
                            ),
                            (
                                "wing_it",
                                "I wing it and trust something fun will happen",
                            ),
                        ],
                        max_length=20,
                        verbose_name="How do you usually approach a challenge?",
                    ),
                ),
                (
                    "quiz_values",
                    models.CharField(
                        choices=[
                            ("clarity", "Clarity and harmony"),
                            ("flexibility", "Flexibility and space"),
                            ("vision", "Long-term vision and clear goals"),
                            ("vibes", "Good vibes and spontaneity"),
                            ("connection", "Connection and support"),
                        ],
                        max_length=20,
                        verbose_name="What do you value most when working with others?",
                    ),
                ),
                (
                    "quiz_compass",
                    models.CharField(
                        choices=[
                            ("logic", "Logic"),
                            ("curiosity", "Curiosity"),
                            ("empathy", "Empathy"),
                            ("vibes", "Vibes"),
                            ("values", "Personal values"),
                        ],
                        max_length=20,
                        verbose_name="When making a decision, what guides you most?",
                    ),
                ),
                (
                    "quiz_day_off",
                    models.CharField(
                        choices=[
                            ("productive", "Getting things done, then relaxing"),
                            ("exploring", "Exploring new places or hobbies"),
                            (
                                "reflecting",
                                "Reflecting or diving into something meaningful",
                            ),
                            ("spontaneous", "Doing whatever feels good in the moment"),
                            ("social", "Connecting with friends"),
                        ],
                        max_length=20,
                        verbose_name="What's your ideal way to spend a day off?",
                    ),
                ),
                (
                    "quiz_friend",
                    models.CharField(
                        choices=[
                            ("supportive", "Sensitive and supportive"),
                            ("uplifting", "Fun and uplifting"),
                            ("imaginative", "Imaginative and adaptable"),
                            ("trustworthy", "Trustworthy and honest"),
                            ("thoughtful", "Thoughtful and purposeful"),
                        ],
                        max_length=20,
                        verbose_name="How would a close friend describe you?",
                    ),
                ),
                (
                    "house_request",
                    models.TextField(
                        blank=True,
                        verbose_name="Do you have any preferences for what house you'd like to be sorted in?",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration",
                        to="courses.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Registration",
                "verbose_name_plural": "Student Registrations",
                "ordering": ("student",),
            },
        ),
        migrations.CreateModel(
            name="CoursePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1 is the most preferred class; blank when excluded",
                        null=True,
                    ),
                ),
                (
                    "excluded",
                    models.BooleanField(
                        default=False,
                        help_text="Set when the student does not want to take this class at all",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="courses.course",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_preferences",
                        to="reg.studentregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Preference",
                "verbose_name_plural": "Course Preferences",
                "ordering": ("excluded", "rank", "course__name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registration", "course"),
                        name="unique_course_per_registration",
                    )
                ],
            },
        ),
    ]
