# Generated by Django 5.2.17 on 2026-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reg", "0004_studentregistration_coursepreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregistration",
            name="completed_steps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Slugs of the questionnaire pages this student has saved. The questionnaire is filled in a page at a time, so a registration missing some of these was abandoned partway.",
            ),
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="difficulty_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Difficulty bands the student would be happy in, e.g. ['aime', 'olympiad']",
            ),
        ),
        migrations.AddField(
            model_name="studentregistration",
            name="subject_interest",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="How interested the student is in each subject, e.g. {'algebra': 'very', ...}",
            ),
        ),
        migrations.AlterField(
            model_name="coursepreference",
            name="rank",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1, 2 or 3 for the student's first, second and third choice; blank when excluded",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentregistration",
            name="taken_class_before",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the student has taken an Athemath class before",
                null=True,
            ),
        ),
    ]
