# Generated by Django 5.2.17 on 2026-08-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reg", "0005_studentregistration_completed_steps_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursepreference",
            options={
                "ordering": ("already_taken", "rank", "course__name"),
                "verbose_name": "Course Preference",
                "verbose_name_plural": "Course Preferences",
            },
        ),
        migrations.RenameField(
            model_name="coursepreference",
            old_name="excluded",
            new_name="already_taken",
        ),
        migrations.AlterField(
            model_name="coursepreference",
            name="already_taken",
            field=models.BooleanField(
                default=False,
                help_text="Set when the student has taken this class before, so they should not be placed in it again",
            ),
        ),
        migrations.AlterField(
            model_name="coursepreference",
            name="rank",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1, 2 or 3 for the student's first, second and third choice; blank for a class they have already taken",
                null=True,
            ),
        ),
    ]
