# Generated by Django 5.2.17 on 2026-08-26 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reg", "0006_alter_coursepreference_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentregistration",
            name="taken_class_before",
        ),
    ]
