# Generated by Django 5.2.8 on 2025-11-16 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0012_semester_house_points_freeze_date_student_house"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("blob", "Blob"),
                            ("cat", "Cat"),
                            ("owl", "Owl"),
                            ("red_panda", "Red Panda"),
                            ("bunny", "Bunny"),
                        ],
                        help_text="For house-level awards only. Auto-filled from student if applicable.",
                        max_length=20,
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[
                            ("intro_post", "Introduction Post"),
                            ("class_attendance", "Class Attendance"),
                            ("homework", "Homework Submission"),
                            ("event", "Club/Seminar/Event Attendance"),
                            ("office_hours", "Office Hours"),
                            ("potd_top3", "PotD Top 3"),
                            ("potd_4_10", "PotD Place 4-10"),
                            ("staff_bonus", "Staff Bonus"),
                            ("house_activity", "House Activity Bonus"),
                            ("other", "Other"),
                        ],
                        help_text="Type of activity that earned these points.",
                        max_length=30,
                    ),
                ),
                ("points", models.IntegerField(help_text="Number of points awarded.")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this award.",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this award was given.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who awarded these points.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="courses.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Student receiving the award. Leave blank for house-level awards.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="courses.student",
                    ),
                ),
            ],
            options={
                "ordering": ("-awarded_at",),
                "indexes": [
                    models.Index(
                        fields=["semester", "house"],
                        name="housepoints_semeste_da76a0_idx",
                    ),
                    models.Index(
                        fields=["semester", "student"],
                        name="housepoints_semeste_e16dd2_idx",
                    ),
                    models.Index(
                        fields=["awarded_at"], name="housepoints_awarded_ec15cf_idx"
                    ),
                ],
            },
        ),
    ]
