# Generated by Django 5.2.8 on 2025-11-20 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_merge_20251119_2128"),
        ("housepoints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="award",
            constraint=models.UniqueConstraint(
                condition=models.Q(("award_type", "intro_post")),
                fields=("semester", "student"),
                name="unique_intro_post_per_student",
            ),
        ),
    ]
