# Generated by Django 5.2.8 on 2025-11-22 17:26

from django.db import migrations, models


def merge_potd_types(apps, schema_editor):
    """Convert potd_top3 and potd_4_10 to the unified potd type."""
    Award = apps.get_model("housepoints", "Award")
    Award.objects.filter(award_type__in=["potd_top3", "potd_4_10"]).update(
        award_type="potd"
    )


def reverse_merge_potd_types(apps, schema_editor):
    """Reverse migration: convert potd back to potd_4_10 (default)."""
    Award = apps.get_model("housepoints", "Award")
    Award.objects.filter(award_type="potd").update(award_type="potd_4_10")


class Migration(migrations.Migration):
    dependencies = [
        ("housepoints", "0002_award_unique_intro_post_per_student"),
    ]

    operations = [
        # First, convert existing data
        migrations.RunPython(merge_potd_types, reverse_merge_potd_types),
        # Then, update the field choices
        migrations.AlterField(
            model_name="award",
            name="award_type",
            field=models.CharField(
                choices=[
                    ("intro_post", "Introduction Post"),
                    ("class_attendance", "Class Attendance"),
                    ("homework", "Homework Submission"),
                    ("event", "Club/Seminar/Event Attendance"),
                    ("office_hours", "Office Hours"),
                    ("potd", "Problem of the Day"),
                    ("staff_bonus", "Staff Bonus"),
                    ("house_activity", "House Activity Bonus"),
                    ("other", "Other"),
                ],
                help_text="Type of activity that earned these points.",
                max_length=30,
            ),
        ),
    ]
