# Generated by Django 5.2.8 on 2025-11-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("housepoints", "0003_merge_potd_award_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="house",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blob", "Blobs"),
                    ("cat", "Cats"),
                    ("owl", "Owls"),
                    ("red_panda", "Red Panda"),
                    ("bunny", "Bunnies"),
                ],
                help_text="For house-level awards only. Auto-filled from student if applicable.",
                max_length=20,
            ),
        ),
    ]
