# Generated by Django 5.2.8 on 2025-11-22 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0019_alter_student_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearbookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="How you want your name displayed to other students.",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Tell us about yourself! (Max 1000 characters)",
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                (
                    "discord_username",
                    models.CharField(
                        blank=True,
                        help_text="Your Discord username (e.g., username#1234 or just username).",
                        max_length=100,
                    ),
                ),
                (
                    "instagram_username",
                    models.CharField(
                        blank=True,
                        help_text="Your Instagram username (without the @).",
                        max_length=100,
                    ),
                ),
                (
                    "github_username",
                    models.CharField(
                        blank=True, help_text="Your GitHub username.", max_length=100
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Your personal website URL."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearbook_entry",
                        to="courses.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yearbook Entry",
                "verbose_name_plural": "Yearbook Entries",
                "ordering": ("student__house", "display_name"),
            },
        ),
    ]
