# Generated by Django 5.2.8 on 2025-11-22 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yearbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearbookentry",
            name="bio",
            field=models.TextField(
                help_text="Tell us about yourself!",
                validators=[django.core.validators.MaxLengthValidator(256)],
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="discord_username",
            field=models.CharField(
                blank=True,
                help_text="Optional. Your Discord username (e.g., username#1234 or just username).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="Optional. Your GitHub username.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="instagram_username",
            field=models.CharField(
                blank=True,
                help_text="Optional. Your Instagram username (without the @).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="website_url",
            field=models.URLField(
                blank=True, help_text="Optional. Your personal website URL."
            ),
        ),
    ]
