# Generated by Django 5.2.8 on 2025-11-22 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yearbook", "0002_alter_yearbookentry_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearbookentry",
            name="bio",
            field=models.TextField(
                help_text="Tell us about yourself!",
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
    ]
