# Generated by Django 5.2.8 on 2025-12-08 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yearbook", "0003_alter_yearbookentry_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearbookentry",
            name="bio",
            field=models.TextField(
                help_text="Tell us about yourself!",
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
    ]
