# Generated by Django 5.2.17 on 2026-09-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0027_course_is_office_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Where is your problem from? If it's a general question, describe what it's about.",
                        max_length=80,
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Write out your question. LaTeX between dollar signs, like $x^2+1$, will be typeset."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for staff; students do not see these.",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="The office hours sitting to answer this at. Left empty, the question is answered over Discord DM instead.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="courses.coursemeeting",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="courses.student",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
